# Generated by Django 5.1.4 on 2024-12-08 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoCorda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_trastes', models.PositiveIntegerField()),
                ('numero_cordas', models.PositiveIntegerField()),
                ('captadores', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_corpo', models.CharField(blank=True, choices=[('classico', 'Clássico'), ('folk', 'Folk'), ('jumbo', 'Jumbo'), ('flat', 'Flat'), ('outros', 'Outros')], max_length=50, null=True)),
                ('cor', models.CharField(max_length=30)),
                ('tipo_instrumento', models.CharField(choices=[('guitarra', 'Guitarra'), ('violao', 'Violão'), ('baixo', 'Baixo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoPercussao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('madeira', 'Madeira'), ('metal', 'Metal'), ('sintetico', 'Sintético')], max_length=50)),
                ('altura', models.PositiveIntegerField()),
                ('tipo_percussao', models.CharField(max_length=50)),
                ('diametro', models.PositiveIntegerField()),
                ('altura_casca', models.PositiveIntegerField()),
                ('tipo_instrumento', models.CharField(choices=[('tambor', 'Tambor'), ('timbal', 'Timbal'), ('xilofone', 'Xilofone'), ('maracas', 'Maracas'), ('triangulo', 'Triângulo'), ('caixa', 'Caixa')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoSopro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('metal', 'Metal'), ('madeira', 'Madeira')], max_length=50)),
                ('alcance', models.CharField(choices=[('baixo', 'Baixo'), ('alto', 'Alto'), ('tenor', 'Tenor')], max_length=50)),
                ('tipo_bocal', models.CharField(max_length=50)),
                ('quantidade_valvulas', models.PositiveIntegerField()),
                ('afinacao', models.CharField(max_length=50)),
                ('tipo_instrumento', models.CharField(choices=[('flauta', 'Flauta'), ('clarinete', 'Clarinete'), ('saxofone', 'Saxofone'), ('trompete', 'Trompete'), ('trombone', 'Trombone'), ('oboé', 'Oboé')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_corda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_corda', to='produtos.instrumentocorda')),
                ('instrumento_percussao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_percussao', to='produtos.instrumentopercussao')),
                ('instrumento_sopro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_sopro', to='produtos.instrumentosopro')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produto_instrumento', to='produtos.produto')),
            ],
        ),
    ]
