# Generated by Django 5.1.4 on 2024-12-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guitarra',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('numero_trastes', models.PositiveIntegerField()),
                ('numero_cordas', models.PositiveIntegerField()),
                ('captadores', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guitarra', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Baixo',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('numero_trastes', models.PositiveIntegerField()),
                ('numero_cordas', models.PositiveIntegerField()),
                ('captadores', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baixo', to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Violao',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('numero_trastes', models.PositiveIntegerField()),
                ('numero_cordas', models.PositiveIntegerField()),
                ('tipo_corpo', models.CharField(choices=[('classico', 'Clássico'), ('folk', 'Folk'), ('jumbo', 'Jumbo'), ('flat', 'Flat'), ('outros', 'Outros')], max_length=10)),
                ('tipo_corda', models.CharField(choices=[('nylon', 'Nylon'), ('aco', 'Aço')], max_length=10)),
                ('cor', models.CharField(max_length=50)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violao', to='produtos.produto')),
            ],
        ),
    ]
