# Generated by Django 5.1.4 on 2025-01-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentopercussao',
            name='tipo_instrumento',
            field=models.CharField(choices=[('tambor', 'Tambor'), ('timbal', 'Timbal'), ('xilofone', 'Xilofone'), ('maracas', 'Maracas'), ('triangulo', 'Triângulo'), ('caixa', 'Caixa'), ('bateria', 'Bateria')], max_length=50),
        ),
    ]
