# Generated by Django 5.1.4 on 2024-12-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPedido',
            new_name='PedidoProduto',
        ),
    ]
